apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mongodb
  annotations:
    # In this case, the application version will match the component one.
    version: "jammy"
    description: "MongoDB database"
spec:
  components:
    - name: mongodb
      type: webservice
      properties:
        image: mongo:latest
        cpu: "150m"
        memory: 256Mi
        ports:
          - port: 27017
            expose: true
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"
    - name: mongo-visualizer
      type: webservice
      properties:
        image: mongo-express
        cpu: "150m"
        memory: 256Mi
        ports:
          - port: 8081
            expose: true
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongodb"
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "root"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "example"
      traits:
        - type: napptive-ingress
          properties:
            name: mongo-visualizer
            port: 8081
            path: /


